server:
  image: node:6.11.2
  command: node ./server/index.js
  working_dir: /app
  volumes:
    - ./backend:/app
  environment:
    PORT: 3000
  ports:
    - "3000:3000"
  links:
    - mongodb

mongodb:
  image: mongo
  ports:
      - "27017:27017"
