server:
  image: node:6.11.2
  command: node ./server/index.js
  working_dir: /app
  volumes:
    - ./backend:/app
  environment:
    - dburl:"mongodb://192.168.0.1:27017"
  ports:
    - "3000:3000"
  links:
    - mongodb

mongodb:
  image:  mongo:3.4
  expose:
     - "27017"
  volumes:
     - "/db/dbdata:/data/db -d"
  ports:
     - "27017:27017"
